import {
  Injectable,
  NotFoundException,
  ConflictException,
  Logger,
} from '@nestjs/common';
import { EventEmitter2 } from '@nestjs/event-emitter';
import { PrismaService } from '@database/prisma.service';
import type { Product, ProductStatus as PrismaProductStatus } from '@generated/prisma/client';
import type {
  CreateProductInput,
  UpdateProductInput,
  ListProductsInput,
  ProductStatus,
} from '@trafi/types';

/**
 * Product response type for API consumers
 */
export interface ProductResponseDto {
  id: string;
  storeId: string;
  name: string;
  slug: string;
  description: string | null;
  priceInCents: number;
  status: ProductStatus;
  productType: string | null;
  vendor: string | null;
  tags: string[];
  createdAt: Date;
  updatedAt: Date;
}

/**
 * Paginated products response
 */
export interface PaginatedProductsDto {
  items: ProductResponseDto[];
  total: number;
  page: number;
  limit: number;
  totalPages: number;
}

/**
 * Products management service
 *
 * IMPORTANT: Use `protected` methods (not `private`) to support
 * merchant overrides in @trafi/core distribution model (RETRO-2).
 *
 * Key behaviors:
 * - Products are tenant-scoped via storeId (defense-in-depth)
 * - IDs automatically generated with prod_ prefix via PrismaService extension
 * - Slugs are auto-generated if not provided
 * - Emits events for product changes
 *
 * @see Story 3.1 - Product Model and Basic CRUD
 * @see Story 3.R2 - Prefixed IDs Foundation
 */
@Injectable()
export class ProductsService {
  protected readonly logger = new Logger(ProductsService.name);

  constructor(
    protected readonly prisma: PrismaService,
    protected readonly eventEmitter: EventEmitter2,
  ) {}

  /**
   * Generate a URL-safe slug from product name.
   * Protected for @trafi/core consumers to customize slug generation.
   *
   * @param name - Product name to slugify
   * @returns URL-safe slug
   */
  protected generateSlug(name: string): string {
    return name
      .toLowerCase()
      .trim()
      .replace(/[^\w\s-]/g, '') // Remove special characters
      .replace(/[\s_-]+/g, '-') // Replace spaces/underscores with hyphens
      .replace(/^-+|-+$/g, ''); // Remove leading/trailing hyphens
  }

  /**
   * Validate that a slug is unique within a store.
   * Protected for merchant override.
   *
   * Only checks against active (non-deleted) products.
   *
   * @param storeId - Store ID for tenant scoping
   * @param slug - Slug to validate
   * @param excludeId - Product ID to exclude (for updates)
   * @throws ConflictException if slug already exists
   * @see Story M-1 - V3 Architectural Retroactive Fixes (AC2)
   */
  protected async validateSlugUnique(
    storeId: string,
    slug: string,
    excludeId?: string,
  ): Promise<void> {
    const existing = await this.prisma.product.findFirst({
      where: {
        storeId,
        slug,
        deletedAt: null, // Only check against active products
        ...(excludeId && { NOT: { id: excludeId } }),
      },
    });

    if (existing) {
      throw new ConflictException(`Product with slug "${slug}" already exists`);
    }
  }

  /**
   * Create a new product.
   *
   * ID is automatically generated with prod_ prefix by PrismaService extension.
   * @see Story 3.R2 - Prefixed IDs Foundation
   *
   * @param storeId - Store ID for tenant isolation
   * @param input - Product creation data
   * @returns Created product
   */
  async create(storeId: string, input: CreateProductInput): Promise<ProductResponseDto> {
    // Generate or validate slug
    const slug = input.slug || this.generateSlug(input.name);
    await this.validateSlugUnique(storeId, slug);

    // Create product - ID is auto-generated by prefixed IDs extension
    const product = await this.prisma.product.create({
      data: {
        storeId,
        name: input.name,
        slug,
        description: input.description ?? null,
        priceInCents: input.priceInCents,
        status: this.toPrismaStatus(input.status ?? 'draft'),
        productType: input.productType ?? null,
        vendor: input.vendor ?? null,
        tags: input.tags ?? [],
      },
    });

    const response = this.toProductResponse(product);

    // Emit event for analytics and side effects
    this.eventEmitter.emit('product.created', {
      product: response,
      storeId,
      timestamp: new Date().toISOString(),
    });

    this.logger.log(`Product created: ${product.id} in store ${storeId}`);

    return response;
  }

  /**
   * Update an existing product.
   *
   * @param storeId - Store ID for tenant isolation
   * @param productId - Product ID to update
   * @param input - Update data
   * @returns Updated product
   */
  async update(
    storeId: string,
    productId: string,
    input: UpdateProductInput,
  ): Promise<ProductResponseDto> {
    // Find existing product (with tenant check, exclude deleted)
    const existing = await this.prisma.product.findFirst({
      where: { id: productId, storeId, deletedAt: null },
    });

    if (!existing) {
      throw new NotFoundException('Product not found');
    }

    // Validate slug uniqueness if being changed
    if (input.slug && input.slug !== existing.slug) {
      await this.validateSlugUnique(storeId, input.slug, productId);
    }

    // Build update data
    const updateData = this.buildUpdateData(input, existing);

    // Update product
    const product = await this.prisma.product.update({
      where: { id: productId },
      data: updateData,
    });

    const response = this.toProductResponse(product);

    // Emit event
    this.eventEmitter.emit('product.updated', {
      product: response,
      previousStatus: existing.status,
      storeId,
      timestamp: new Date().toISOString(),
    });

    this.logger.log(`Product updated: ${productId} in store ${storeId}`);

    return response;
  }

  /**
   * Soft delete a product (sets deletedAt timestamp).
   *
   * Per Principle #9: High-value business data uses deletedAt for soft deletes.
   * Products are referenced by order history and analytics, so they should
   * never be truly deleted.
   *
   * @param storeId - Store ID for tenant isolation
   * @param productId - Product ID to delete
   * @see Story M-1 - V3 Architectural Retroactive Fixes (AC2)
   */
  async delete(storeId: string, productId: string): Promise<void> {
    // Find existing product (with tenant check, exclude already deleted)
    const existing = await this.prisma.product.findFirst({
      where: { id: productId, storeId, deletedAt: null },
    });

    if (!existing) {
      throw new NotFoundException('Product not found');
    }

    // Soft delete: set deletedAt timestamp instead of hard delete
    await this.prisma.product.update({
      where: { id: productId },
      data: { deletedAt: new Date() },
    });

    // Emit event
    this.eventEmitter.emit('product.deleted', {
      productId,
      storeId,
      timestamp: new Date().toISOString(),
    });

    this.logger.log(`Product soft-deleted: ${productId} from store ${storeId}`);
  }

  /**
   * Get a product by ID.
   *
   * Filters out soft-deleted products by default.
   *
   * @param storeId - Store ID for tenant isolation
   * @param productId - Product ID
   * @returns Product or throws NotFoundException
   * @see Story M-1 - V3 Architectural Retroactive Fixes (AC2)
   */
  async findById(storeId: string, productId: string): Promise<ProductResponseDto> {
    const product = await this.prisma.product.findFirst({
      where: { id: productId, storeId, deletedAt: null },
    });

    if (!product) {
      throw new NotFoundException('Product not found');
    }

    return this.toProductResponse(product);
  }

  /**
   * Get a product by ID including soft-deleted products.
   *
   * Admin-only method for viewing/restoring deleted products.
   *
   * @param storeId - Store ID for tenant isolation
   * @param productId - Product ID
   * @returns Product (including deleted) or throws NotFoundException
   * @see Story M-1 - V3 Architectural Retroactive Fixes (AC2)
   */
  async findByIdIncludingDeleted(storeId: string, productId: string): Promise<ProductResponseDto & { deletedAt: Date | null }> {
    const product = await this.prisma.product.findFirst({
      where: { id: productId, storeId },
    });

    if (!product) {
      throw new NotFoundException('Product not found');
    }

    return {
      ...this.toProductResponse(product),
      deletedAt: product.deletedAt,
    };
  }

  /**
   * Restore a soft-deleted product.
   *
   * Admin-only method for restoring deleted products.
   *
   * @param storeId - Store ID for tenant isolation
   * @param productId - Product ID to restore
   * @returns Restored product
   * @see Story M-1 - V3 Architectural Retroactive Fixes (AC2)
   */
  async restore(storeId: string, productId: string): Promise<ProductResponseDto> {
    // Find product (including deleted)
    const existing = await this.prisma.product.findFirst({
      where: { id: productId, storeId },
    });

    if (!existing) {
      throw new NotFoundException('Product not found');
    }

    if (!existing.deletedAt) {
      throw new ConflictException('Product is not deleted');
    }

    // Restore: clear deletedAt
    const product = await this.prisma.product.update({
      where: { id: productId },
      data: { deletedAt: null },
    });

    // Emit event
    this.eventEmitter.emit('product.restored', {
      product: this.toProductResponse(product),
      storeId,
      timestamp: new Date().toISOString(),
    });

    this.logger.log(`Product restored: ${productId} in store ${storeId}`);

    return this.toProductResponse(product);
  }

  /**
   * List products with pagination and filtering.
   *
   * @param storeId - Store ID for tenant isolation
   * @param input - Pagination and filter options
   * @returns Paginated products list
   */
  async list(storeId: string, input: ListProductsInput): Promise<PaginatedProductsDto> {
    const { page = 1, limit = 20, sortBy, sortOrder = 'desc', status, search, productType, vendor, tags } = input;
    const skip = (page - 1) * limit;

    // Build where clause
    const where = this.buildWhereClause(storeId, { status, search, productType, vendor, tags });

    // Build orderBy
    const orderBy = this.buildOrderBy(sortBy, sortOrder);

    // Execute query with count
    const [items, total] = await this.prisma.$transaction([
      this.prisma.product.findMany({
        where,
        orderBy,
        skip,
        take: limit,
      }),
      this.prisma.product.count({ where }),
    ]);

    return {
      items: items.map((item) => this.toProductResponse(item)),
      total,
      page,
      limit,
      totalPages: Math.ceil(total / limit),
    };
  }

  /**
   * Build Prisma where clause for list query.
   * Protected for merchant override.
   *
   * Always filters out soft-deleted products (deletedAt: null).
   * @see Story M-1 - V3 Architectural Retroactive Fixes (AC2)
   */
  protected buildWhereClause(
    storeId: string,
    filters: {
      status?: ProductStatus;
      search?: string;
      productType?: string;
      vendor?: string;
      tags?: string[];
    },
  ) {
    // Always exclude soft-deleted products
    const where: Record<string, unknown> = { storeId, deletedAt: null };

    if (filters.status) {
      where.status = this.toPrismaStatus(filters.status);
    }

    if (filters.productType) {
      where.productType = filters.productType;
    }

    if (filters.vendor) {
      where.vendor = filters.vendor;
    }

    if (filters.tags && filters.tags.length > 0) {
      where.tags = { hasSome: filters.tags };
    }

    if (filters.search) {
      where.OR = [
        { name: { contains: filters.search, mode: 'insensitive' } },
        { description: { contains: filters.search, mode: 'insensitive' } },
        { vendor: { contains: filters.search, mode: 'insensitive' } },
      ];
    }

    return where;
  }

  /**
   * Build Prisma orderBy clause.
   * Protected for merchant override.
   */
  protected buildOrderBy(
    sortBy?: string,
    sortOrder: 'asc' | 'desc' = 'desc',
  ): Record<string, 'asc' | 'desc'> {
    const validSortFields = ['name', 'createdAt', 'updatedAt', 'priceInCents', 'status'];
    const field = sortBy && validSortFields.includes(sortBy) ? sortBy : 'createdAt';
    return { [field]: sortOrder };
  }

  /**
   * Build update data from input, only including changed fields.
   * Protected for merchant override.
   */
  protected buildUpdateData(
    input: UpdateProductInput,
    _existing: Product,
  ): Record<string, unknown> {
    const data: Record<string, unknown> = {};

    if (input.name !== undefined) data.name = input.name;
    if (input.slug !== undefined) data.slug = input.slug;
    if (input.description !== undefined) data.description = input.description;
    if (input.priceInCents !== undefined) data.priceInCents = input.priceInCents;
    if (input.status !== undefined) data.status = this.toPrismaStatus(input.status);
    if (input.productType !== undefined) data.productType = input.productType;
    if (input.vendor !== undefined) data.vendor = input.vendor;
    if (input.tags !== undefined) data.tags = input.tags;

    return data;
  }

  /**
   * Convert Prisma Product to API response.
   * Protected for @trafi/core customization.
   */
  protected toProductResponse(product: Product): ProductResponseDto {
    return {
      id: product.id,
      storeId: product.storeId,
      name: product.name,
      slug: product.slug,
      description: product.description,
      priceInCents: product.priceInCents,
      status: this.toApiStatus(product.status),
      productType: product.productType,
      vendor: product.vendor,
      tags: product.tags,
      createdAt: product.createdAt,
      updatedAt: product.updatedAt,
    };
  }

  /**
   * Convert API status to Prisma enum.
   */
  protected toPrismaStatus(status: ProductStatus): PrismaProductStatus {
    const map: Record<ProductStatus, PrismaProductStatus> = {
      draft: 'DRAFT',
      active: 'ACTIVE',
      archived: 'ARCHIVED',
    };
    return map[status];
  }

  /**
   * Convert Prisma enum to API status.
   */
  protected toApiStatus(status: PrismaProductStatus): ProductStatus {
    const map: Record<PrismaProductStatus, ProductStatus> = {
      DRAFT: 'draft',
      ACTIVE: 'active',
      ARCHIVED: 'archived',
    };
    return map[status];
  }
}
