import {
  Injectable,
  NotFoundException,
  ConflictException,
  BadRequestException,
  Logger,
} from '@nestjs/common';
import { EventEmitter2 } from '@nestjs/event-emitter';
import { PrismaService } from '@database/prisma.service';
import type { Collection } from '@generated/prisma/client';
import type {
  CreateCollectionInput,
  UpdateCollectionInput,
  AddProductsToCollectionInput,
  RemoveProductsFromCollectionInput,
  ReorderCollectionProductsInput,
  ListCollectionsInput,
  CollectionListItem,
  CollectionListResponse,
} from '@trafi/types';

/**
 * Collection response type for API consumers
 */
export interface CollectionResponseDto {
  id: string;
  storeId: string;
  name: string;
  slug: string;
  description: string | null;
  imageUrl: string | null;
  isVisible: boolean;
  isFeatured: boolean;
  createdAt: Date;
  updatedAt: Date;
  productCount?: number;
}

/**
 * Collection with products response type
 */
export interface CollectionWithProductsDto extends CollectionResponseDto {
  products: {
    productId: string;
    position: number;
    product: {
      id: string;
      name: string;
      slug: string;
      priceInCents: number;
      status: 'DRAFT' | 'ACTIVE' | 'ARCHIVED';
      media?: {
        id: string;
        url: string;
        alt: string | null;
        position: number;
      }[];
    };
  }[];
}

/**
 * Collections management service
 *
 * IMPORTANT: Use `protected` methods (not `private`) to support
 * merchant overrides in @trafi/core distribution model (RETRO-2).
 *
 * Key behaviors:
 * - Collections are tenant-scoped via storeId (defense-in-depth)
 * - IDs automatically generated with col_ prefix via PrismaService extension
 * - Slugs are auto-generated if not provided
 * - Flat structure (no hierarchy, simpler than categories)
 * - Emits events for collection changes
 *
 * @see Story 3.5 - Collections Management
 * @see Story 3.R2 - Prefixed IDs Foundation
 */
@Injectable()
export class CollectionsService {
  protected readonly logger = new Logger(CollectionsService.name);

  constructor(
    protected readonly prisma: PrismaService,
    protected readonly eventEmitter: EventEmitter2,
  ) {}

  // ==========================================================================
  // Protected Utility Methods
  // ==========================================================================

  /**
   * Generate a URL-safe slug from collection name.
   * Protected for @trafi/core consumers to customize slug generation.
   *
   * @param name - Collection name to slugify
   * @returns URL-safe slug
   */
  protected generateSlug(name: string): string {
    return name
      .toLowerCase()
      .trim()
      .replace(/[^\w\s-]/g, '') // Remove special characters
      .replace(/[\s_-]+/g, '-') // Replace spaces/underscores with hyphens
      .replace(/^-+|-+$/g, ''); // Remove leading/trailing hyphens
  }

  /**
   * Validate that a slug is unique within a store.
   * Protected for merchant override.
   *
   * @param storeId - Store ID for tenant scoping
   * @param slug - Slug to validate
   * @param excludeId - Collection ID to exclude (for updates)
   * @throws ConflictException if slug already exists
   */
  protected async validateSlugUnique(
    storeId: string,
    slug: string,
    excludeId?: string,
  ): Promise<void> {
    const existing = await this.prisma.collection.findFirst({
      where: {
        storeId,
        slug,
        ...(excludeId && { NOT: { id: excludeId } }),
      },
    });

    if (existing) {
      throw new ConflictException(`Collection with slug "${slug}" already exists`);
    }
  }

  // ==========================================================================
  // CRUD Methods
  // ==========================================================================

  /**
   * Create a new collection.
   *
   * ID is automatically generated with col_ prefix by PrismaService extension.
   * @see Story 3.R2 - Prefixed IDs Foundation
   *
   * @param storeId - Store ID for tenant isolation
   * @param input - Collection creation data
   * @returns Created collection
   */
  async create(storeId: string, input: CreateCollectionInput): Promise<CollectionResponseDto> {
    // Generate or validate slug
    const slug = input.slug || this.generateSlug(input.name);
    await this.validateSlugUnique(storeId, slug);

    // Create collection - ID is auto-generated by prefixed IDs extension
    const collection = await this.prisma.collection.create({
      data: {
        storeId,
        name: input.name,
        slug,
        description: input.description ?? null,
        imageUrl: input.imageUrl ?? null,
        isVisible: input.isVisible ?? true,
        isFeatured: input.isFeatured ?? false,
      },
    });

    const response = this.toCollectionResponse(collection);

    // Emit event for analytics and side effects
    this.eventEmitter.emit('collection.created', {
      collection: response,
      storeId,
      timestamp: new Date().toISOString(),
    });

    this.logger.log(`Collection created: ${collection.id} in store ${storeId}`);

    return response;
  }

  /**
   * Update an existing collection.
   *
   * @param storeId - Store ID for tenant isolation
   * @param input - Update data
   * @returns Updated collection
   */
  async update(storeId: string, input: UpdateCollectionInput): Promise<CollectionResponseDto> {
    // Find existing collection (with tenant check)
    const existing = await this.prisma.collection.findFirst({
      where: { id: input.id, storeId },
    });

    if (!existing) {
      throw new NotFoundException('Collection not found');
    }

    // Validate slug uniqueness if being changed
    if (input.slug && input.slug !== existing.slug) {
      await this.validateSlugUnique(storeId, input.slug, input.id);
    }

    // Build update data
    const updateData: Record<string, unknown> = {};
    if (input.name !== undefined) updateData.name = input.name;
    if (input.slug !== undefined) updateData.slug = input.slug;
    if (input.description !== undefined) updateData.description = input.description;
    if (input.imageUrl !== undefined) updateData.imageUrl = input.imageUrl;
    if (input.isVisible !== undefined) updateData.isVisible = input.isVisible;
    if (input.isFeatured !== undefined) updateData.isFeatured = input.isFeatured;

    // Update collection
    const collection = await this.prisma.collection.update({
      where: { id: input.id },
      data: updateData,
    });

    const response = this.toCollectionResponse(collection);

    // Emit event
    this.eventEmitter.emit('collection.updated', {
      collection: response,
      storeId,
      timestamp: new Date().toISOString(),
    });

    this.logger.log(`Collection updated: ${input.id} in store ${storeId}`);

    return response;
  }

  /**
   * Delete a collection.
   * Products assigned to this collection will have their assignment removed,
   * but the products themselves will NOT be deleted.
   *
   * @param storeId - Store ID for tenant isolation
   * @param collectionId - Collection ID to delete
   */
  async delete(storeId: string, collectionId: string): Promise<void> {
    // Find existing collection
    const existing = await this.prisma.collection.findFirst({
      where: { id: collectionId, storeId },
    });

    if (!existing) {
      throw new NotFoundException('Collection not found');
    }

    // Delete collection (CollectionProduct entries cascade automatically)
    await this.prisma.collection.delete({ where: { id: collectionId } });

    // Emit event
    this.eventEmitter.emit('collection.deleted', {
      collectionId,
      storeId,
      timestamp: new Date().toISOString(),
    });

    this.logger.log(`Collection deleted: ${collectionId} from store ${storeId}`);
  }

  /**
   * Get a collection by ID.
   *
   * @param storeId - Store ID for tenant isolation
   * @param collectionId - Collection ID
   * @returns Collection or throws NotFoundException
   */
  async findById(storeId: string, collectionId: string): Promise<CollectionResponseDto> {
    const collection = await this.prisma.collection.findFirst({
      where: { id: collectionId, storeId },
      include: {
        _count: { select: { products: true } },
      },
    });

    if (!collection) {
      throw new NotFoundException('Collection not found');
    }

    return this.toCollectionResponse(collection, collection._count?.products);
  }

  /**
   * Get a collection with its products.
   *
   * @param storeId - Store ID for tenant isolation
   * @param collectionId - Collection ID
   * @returns Collection with products
   */
  async findByIdWithProducts(storeId: string, collectionId: string): Promise<CollectionWithProductsDto> {
    const collection = await this.prisma.collection.findFirst({
      where: { id: collectionId, storeId },
      include: {
        products: {
          orderBy: { position: 'asc' },
          include: {
            product: {
              include: {
                media: {
                  orderBy: { position: 'asc' },
                  take: 1,
                },
              },
            },
          },
        },
      },
    });

    if (!collection) {
      throw new NotFoundException('Collection not found');
    }

    return {
      id: collection.id,
      storeId: collection.storeId,
      name: collection.name,
      slug: collection.slug,
      description: collection.description,
      imageUrl: collection.imageUrl,
      isVisible: collection.isVisible,
      isFeatured: collection.isFeatured,
      createdAt: collection.createdAt,
      updatedAt: collection.updatedAt,
      productCount: collection.products.length,
      products: collection.products.map((cp) => ({
        productId: cp.productId,
        position: cp.position,
        product: {
          id: cp.product.id,
          name: cp.product.name,
          slug: cp.product.slug,
          priceInCents: cp.product.priceInCents,
          status: cp.product.status,
          media: cp.product.media.map((m: { id: string; url: string; altText: string | null; position: number }) => ({
            id: m.id,
            url: m.url,
            alt: m.altText,
            position: m.position,
          })),
        },
      })),
    };
  }

  /**
   * List collections with pagination and filters.
   *
   * @param storeId - Store ID for tenant isolation
   * @param input - List options
   * @returns Paginated collection list
   */
  async list(
    storeId: string,
    input: Partial<ListCollectionsInput> = {},
  ): Promise<CollectionListResponse> {
    const { page = 1, limit = 20, isVisible, isFeatured, search } = input;
    const skip = (page - 1) * limit;

    // Build where clause
    const where: Record<string, unknown> = { storeId };
    if (isVisible !== undefined) where.isVisible = isVisible;
    if (isFeatured !== undefined) where.isFeatured = isFeatured;
    if (search) {
      where.OR = [
        { name: { contains: search, mode: 'insensitive' } },
        { description: { contains: search, mode: 'insensitive' } },
      ];
    }

    // Get collections and total count
    const [collections, total] = await Promise.all([
      this.prisma.collection.findMany({
        where,
        include: {
          _count: { select: { products: true } },
        },
        orderBy: [{ isFeatured: 'desc' }, { createdAt: 'desc' }],
        skip,
        take: limit,
      }),
      this.prisma.collection.count({ where }),
    ]);

    return {
      collections: collections.map((c) => ({
        id: c.id,
        name: c.name,
        slug: c.slug,
        description: c.description,
        imageUrl: c.imageUrl,
        isVisible: c.isVisible,
        isFeatured: c.isFeatured,
        createdAt: c.createdAt,
        updatedAt: c.updatedAt,
        productCount: c._count?.products ?? 0,
      })),
      total,
      page,
      limit,
      totalPages: Math.ceil(total / limit),
    };
  }

  // ==========================================================================
  // Product Assignment Methods
  // ==========================================================================

  /**
   * Add products to a collection.
   *
   * @param storeId - Store ID for tenant isolation
   * @param input - Assignment data
   */
  async addProducts(storeId: string, input: AddProductsToCollectionInput): Promise<void> {
    // Verify collection belongs to store
    const collection = await this.prisma.collection.findFirst({
      where: { id: input.collectionId, storeId },
    });

    if (!collection) {
      throw new NotFoundException('Collection not found');
    }

    // Verify all products belong to store
    const products = await this.prisma.product.findMany({
      where: {
        id: { in: input.productIds },
        storeId,
        deletedAt: null,
      },
      select: { id: true },
    });

    if (products.length !== input.productIds.length) {
      throw new BadRequestException('One or more products not found');
    }

    // Get max position for ordering
    const maxPosition = await this.prisma.collectionProduct.aggregate({
      where: { collectionId: input.collectionId },
      _max: { position: true },
    });
    let nextPosition = (maxPosition._max?.position ?? -1) + 1;

    // Create assignments (skip existing)
    await this.prisma.$transaction(
      input.productIds.map((productId) =>
        this.prisma.collectionProduct.upsert({
          where: {
            collectionId_productId: { collectionId: input.collectionId, productId },
          },
          update: {}, // No update needed, keep existing position
          create: {
            productId,
            collectionId: input.collectionId,
            position: nextPosition++,
          },
        }),
      ),
    );

    // Emit event
    this.eventEmitter.emit('collection.updated', {
      collectionId: input.collectionId,
      storeId,
      action: 'products_added',
      productIds: input.productIds,
      timestamp: new Date().toISOString(),
    });

    this.logger.log(
      `Added ${input.productIds.length} products to collection ${input.collectionId} in store ${storeId}`,
    );
  }

  /**
   * Remove products from a collection.
   *
   * @param storeId - Store ID for tenant isolation
   * @param input - Removal data
   */
  async removeProducts(storeId: string, input: RemoveProductsFromCollectionInput): Promise<void> {
    // Verify collection belongs to store
    const collection = await this.prisma.collection.findFirst({
      where: { id: input.collectionId, storeId },
    });

    if (!collection) {
      throw new NotFoundException('Collection not found');
    }

    // Delete assignments
    await this.prisma.collectionProduct.deleteMany({
      where: {
        collectionId: input.collectionId,
        productId: { in: input.productIds },
      },
    });

    // Emit event
    this.eventEmitter.emit('collection.updated', {
      collectionId: input.collectionId,
      storeId,
      action: 'products_removed',
      productIds: input.productIds,
      timestamp: new Date().toISOString(),
    });

    this.logger.log(
      `Removed ${input.productIds.length} products from collection ${input.collectionId} in store ${storeId}`,
    );
  }

  /**
   * Reorder products within a collection.
   *
   * @param storeId - Store ID for tenant isolation
   * @param input - Reorder data
   */
  async reorderProducts(storeId: string, input: ReorderCollectionProductsInput): Promise<void> {
    // Verify collection belongs to store
    const collection = await this.prisma.collection.findFirst({
      where: { id: input.collectionId, storeId },
    });

    if (!collection) {
      throw new NotFoundException('Collection not found');
    }

    // Update positions in transaction
    await this.prisma.$transaction(
      input.productIds.map((productId, index) =>
        this.prisma.collectionProduct.update({
          where: {
            collectionId_productId: { collectionId: input.collectionId, productId },
          },
          data: { position: index },
        }),
      ),
    );

    // Emit event
    this.eventEmitter.emit('collection.updated', {
      collectionId: input.collectionId,
      storeId,
      action: 'products_reordered',
      timestamp: new Date().toISOString(),
    });

    this.logger.log(`Reordered products in collection ${input.collectionId} in store ${storeId}`);
  }

  /**
   * Get product count for a collection.
   *
   * @param storeId - Store ID for tenant isolation
   * @param collectionId - Collection ID
   * @returns Number of products in the collection
   */
  async getProductCount(storeId: string, collectionId: string): Promise<number> {
    // Verify collection belongs to store
    const collection = await this.prisma.collection.findFirst({
      where: { id: collectionId, storeId },
    });

    if (!collection) {
      throw new NotFoundException('Collection not found');
    }

    return this.prisma.collectionProduct.count({
      where: { collectionId },
    });
  }

  /**
   * Get collections assigned to a specific product.
   *
   * @param storeId - Store ID for tenant isolation
   * @param productId - Product ID
   * @returns List of collections assigned to the product
   */
  async getCollectionsForProduct(storeId: string, productId: string): Promise<CollectionListItem[]> {
    const assignments = await this.prisma.collectionProduct.findMany({
      where: {
        productId,
        collection: { storeId },
      },
      include: {
        collection: true,
      },
      orderBy: { position: 'asc' },
    });

    return assignments.map((a) => ({
      id: a.collection.id,
      name: a.collection.name,
      slug: a.collection.slug,
      description: a.collection.description,
      imageUrl: a.collection.imageUrl,
      isVisible: a.collection.isVisible,
      isFeatured: a.collection.isFeatured,
      createdAt: a.collection.createdAt,
      updatedAt: a.collection.updatedAt,
      productCount: 0, // Not fetched here, just for type compatibility
    }));
  }

  // ==========================================================================
  // Private Helpers
  // ==========================================================================

  /**
   * Convert Prisma Collection to API response.
   * Protected for @trafi/core customization.
   */
  protected toCollectionResponse(
    collection: Collection,
    productCount?: number,
  ): CollectionResponseDto {
    return {
      id: collection.id,
      storeId: collection.storeId,
      name: collection.name,
      slug: collection.slug,
      description: collection.description,
      imageUrl: collection.imageUrl,
      isVisible: collection.isVisible,
      isFeatured: collection.isFeatured,
      createdAt: collection.createdAt,
      updatedAt: collection.updatedAt,
      productCount,
    };
  }
}
